### ISSUE TITLE
Not working with cuda 8.0 and python 3.6 and latest pytorch version 

### ISSUE THREAD

**Issue by manoja328** [facebookresearch/clevr-iep#20]
*Whenever i try to run the program i get the following error.Somebody fix this please*

Loading program generator from  scripts/models/CLEVR/program_generator_18k.pt
Loading execution engine from  scripts/models/CLEVR/execution_engine_18k.pt
Loading CNN for feature extraction
Running the model

Traceback (most recent call last):
  File "run_model.py", line 301, in <module>
    main(args)
  File "run_model.py", line 85, in main
    run_single_example(args, model)
  File "run_model.py", line 159, in run_single_example
    argmax=(args.sample_argmax == 1))
  File "/home/manoj/Desktop/clevr-iep/iep/models/seq2seq.py", line 169, in reinforce_sample
    logprobs, h, c = self.decoder(encoded, cur_input, h0=h, c0=c)
  File "/home/manoj/Desktop/clevr-iep/iep/models/seq2seq.py", line 91, in decoder
    V_in, V_out, D, H, L, N, T_in, T_out = self.get_dims(y=y)
  File "/home/manoj/Desktop/clevr-iep/iep/models/seq2seq.py", line 56, in get_dims
    T_out = y.size(1) if y is not None else None
RuntimeError: invalid argument 2: out of range at /opt/conda/conda-bld/pytorch_1502009910772/work/torch/lib/THC/generic/THCTensor.c:23

**Comment by manoja328** [comment]
The issue is solved ... refer the solved issues sections.

**Comment by greaber** [comment]
@manoja328, I hit this issue by googling the pytorch error message, which I am getting in a different model, and I am hoping maybe there is a similar cause.  But I don't understand what the "solved issues sections" are.  In my case, the model runs for 32 training steps and then either runs out of memory (mysteriously, since memory usage was stable to that point and nothing changed) or dies with this error message.

**Comment by greaber** [comment]
Oh, I see, there was discussion on #17.
